### ISSUE TITLE
Ajouter l'icone et le type de page dans la table des pages

### ISSUE THREAD

**Issue by bertrandgorge** [neayi/insights#100]
https://wiki.tripleperformance.fr/wiki/Sp%C3%A9cial:Parcourir/:Pois-5Fchiche

A un fichier d'icone de caractéristique : Fichier:Fruits.png
A un type de page : Culture

+ filtrer sur le type de page (Culture ou Label) pour l'ajout de caractéristiques

**Comment by bertrandgorge** [comment]
Et supprimer le + : "Pensez à utiliser search la recherche ou à + ajouter vous-même ce qui vous caractérise le mieux."

**Comment by bertrandgorge** [comment]
Exemple de page avec icone et image : https://wiki.tripleperformance.fr/wiki/Techniques_culturales_simplifi%C3%A9es_(TCS)
https://wiki.tripleperformance.fr/wiki/Sp%C3%A9cial:Parcourir/:Techniques-5Fculturales-5Fsimplifi%C3%A9es-5F(TCS)

Exemple de page avec un type : https://wiki.tripleperformance.fr/wiki/Sp%C3%A9cial:Parcourir/:Abricot-5F:-5Fprivil%C3%A9gier-5Fles-5Fobservations-5Fet-5Fle-5Fbiocontr%C3%B4le-5Fpour-5Fbaisser-5Fles-5FIFT (A un type de page	Exemple de mise en œuvre)

**Comment by bertrandgorge** [comment]
https://wiki.tripleperformance.fr/api.php?action=ask&api_version=3&query=[[A%20un%20type%20de%20page::%2B]]|%3FA%20un%20fichier%20d%27icone%20de%20caract%C3%A9ristique|%3FA%20un%20type%20de%20page&format=jsonfm

**Comment by guillaume-cozic** [comment]
#78
