### ISSUE TITLE
Le filtre de recherche des followers de la page n'est pas ok - il faut faire l'union des follow et des done

### ISSUE THREAD

**Issue by bertrandgorge** [neayi/insights#111]
Sur les deux services web (followers et stats), il faut faire la somme des utilisateurs du site qui suivent la page OU qui l'ont fait, pas uniquement ceux qui suivent la page.

- Quand type = do, alors on ne garde que ceux qui ont done=1, indépendamment de follow.
- Quand type != do, on prend tous les utilisateurs avec follow = 1 OR done = 1

**Comment by guillaume-cozic** [comment]
#78 https://github.com/neayi/insights/pull/78/commits/eda28d35f75edfae7ef16242ec61034e87a58421
