### ISSUE TITLE
Dans l'API des stats, le pretty_page_label ne doit pas avoir le prefix "Catégorie:"

### ISSUE THREAD

**Issue by bertrandgorge** [neayi/insights#112]
{
"id": 38,
"uuid": "e37edb89-eb02-49a6-94dd-669d7609d6f6",
"code": "Catégorie:Labels",
"type": "croppingSystem",
"priority": 80,
"main": 0,
"icon": "public/characteristics/e37edb89-eb02-49a6-94dd-669d7609d6f6.png",
"page_id": 4830,
"page_label": "Catégorie:Labels",
"pretty_page_label": "Catégorie:Labels",
"opt": null,
"created_at": "2021-04-21T14:43:20.000000Z",
"updated_at": "2021-06-30T10:33:26.000000Z",
"visible": 1,
"count": 3
}

**Comment by guillaume-cozic** [comment]
#78 https://github.com/neayi/insights/pull/78/commits/bf04e05817225a0b0ee883b21d1ae5ec1bdba048
