### ISSUE TITLE
Quand on va sur /profile sans être connecté, après connexion on est redirigé vers le BO d'insights

### ISSUE THREAD

**Issue by bertrandgorge** [neayi/insights#118]
Il faut rediriger vers le la page /profile

**Comment by guillaume-cozic** [comment]
https://github.com/neayi/insights/pull/78/commits/b2bcd8cafcc9f66314d3de7427b0bb80383809df

**Comment by bertrandgorge** [comment]
Toujours présent... Pour reproduire : 

1. Se connecter sur https://wiki.preprod.tripleperformance.fr/wiki/Triple_Performance
2. Aller sur https://insights.preprod.tripleperformance.fr/user/logout
3. Naviguer sur https://wiki.preprod.tripleperformance.fr/wiki/Triple_Performance
4. Cliquer sur le premier menu sous l'avatar (avec le nom) --> https://insights.preprod.tripleperformance.fr/profile
