### ISSUE TITLE
Problème quand on accède sur le profil de quelqu'un

### ISSUE THREAD

**Issue by bertrandgorge** [neayi/insights#120]
![image (4)](https://user-images.githubusercontent.com/12585613/125048134-e61cc880-e09f-11eb-8b9c-094b3f6c8672.png)

**Comment by bertrandgorge** [comment]
https://insights.preprod.tripleperformance.fr/tp/Astrid%20Robette/6e87e698-dfcc-4b98-a7b0-b1be9ce161c9

**Comment by guillaume-cozic** [comment]
#78 https://github.com/neayi/insights/pull/78/commits/afd7741178cc2a4ea054222d526bf68ec6b23cda
