### ISSUE TITLE
Permettre d'appliquer les mêmes filtres sur l'API stats et sur l'API followers

### ISSUE THREAD

**Issue by bertrandgorge** [neayi/insights#121]
Renvoyer 2 counts : l'un hors filtre (sinon la page) et un deuxième avec le filtre sur le département / follow / production et cahier des charges.

A voir si ce n'est pas trop de boulot.

**Comment by guillaume-cozic** [comment]
https://github.com/neayi/insights/pull/78/commits/1b49fffe614d3ac4bbbdd556847536bde4925ba1

**Comment by guillaume-cozic** [comment]
je ferme car plus de besoin
