### ISSUE TITLE
Sentry - Exception in App\Console\Commands\SyncUsersDiscourse::createUserOnDiscourse at line 68

### ISSUE THREAD

**Issue by bertrandgorge** [neayi/insights#179]
https://neayi.sentry.io/issues/3770124132/?project=5999011

Exception sur la ligne : https://github.com/neayi/insights/blob/master/app/Console/Commands/SyncUsersDiscourse.php#L68

L'exception se manifeste quand on fait tourner le cron : `users:sync-on-discourse` pour le users.id = 16114

**Comment by bertrandgorge** [comment]
Il s'agissait probablement de ceux qui ont créé un compte sans vérifier leur email puis qui se sont connectés avec facebook

**Comment by guillaume-cozic** [comment]
https://github.com/neayi/insights/pull/194
