### ISSUE TITLE
Sentry - Call to a member function toDto() on null

### ISSUE THREAD

**Issue by bertrandgorge** [neayi/insights#181]
https://neayi.sentry.io/issues/3855715636/?project=5999011

https://github.com/neayi/insights/blob/master/app/Src/UseCases/Infra/Sql/InteractionPageRepositorySql.php#L191

`select * from characteristics where code = 93`

`select characteristics.*, user_characteristics.user_id as pivot_user_id, user_characteristics.characteristic_id as pivot_characteristic_id from characteristics inner join user_characteristics on characteristics.id = user_characteristics.characteristic_id where user_characteristics.user_id = 16773`

**Comment by guillaume-cozic** [comment]
C'est lié au pb de context des utilisateurs
