### ISSUE TITLE
La connexion via plusieurs instances du forum ne fonctionnent pas - seul le français fonctionne

### ISSUE THREAD

**Issue by bertrandgorge** [neayi/insights#182]

**Comment by guillaume-cozic** [comment]
Tu as plus d'info sur le pb ?

**Comment by bertrandgorge** [comment]
Oui. Quand j'essaie de me connecter à partir de : https://forum.en.dev.tripleperformance.ag/ il me redirige vers 

https://forum.dev.tripleperformance.fr/session/sso_login?sso=bm9uY2U9YTlkODI1OWRhYTU1YWRkMDgyZmE4MjI4YzRiOWE4ZTkmZXh0ZXJuYWxfaWQ9MSZlbWFpbD1iZXJ0cmFuZC5nb3JnZSU0MG5lYXlpLmNvbSZiaW89Jm5hbWU9QmVydHJhbmQrR29yZ2UmcmVxdWlyZV9hY3RpdmF0aW9uPWZhbHNlJnVzZXJuYW1lPWJlcnRyYW5kLmdvcmdl&sig=ab1b0385a6f31db35e8c146861fc51a9f37f3f76e3aea9ac4137d1fafa26693f

(NB : la redirection va vers le mauvais host)

**Comment by bertrandgorge** [comment]
Est-ce que t'as la possibilité de la mettre en cache ?
