### ISSUE TITLE
Ajouter un attribut dans la réponse à l'API pour savoir si un utilisateur a chargé un avatar

### ISSUE THREAD

**Issue by bertrandgorge** [neayi/insights#201]
Dans l'API, il faudrait ajouter un petit flag pour savoir si l'avatar renvoyé est celui par défaut ou bien une image spécifique pour l'utilisateur...:
https://insights.tripleperformance.fr/api/page/10587/followers?type=follow

**Comment by guillaume-cozic** [comment]
https://github.com/neayi/insights/pull/202
