### ISSUE TITLE
Erreur sur la page profile quand le champ description est null

### ISSUE THREAD

**Issue by bertrandgorge** [neayi/insights#80]
TypeErrorArgument 5 passed to `App\Src\UseCases\Domain\Context\Dto\ContextDto::__construct()` must be of the type string, null given, called in `/var/www/html/app/Src/UseCases/Infra/Sql/ContextRepositorySql.php` on line 70

https://insights.dev.tripleperformance.fr/profile

Le bug n'apparait plus quand je force une donnée non nulle en DB (je créé le bug)

**Comment by bertrandgorge** [comment]
Est-ce que ce commit corrige ce bug du coup ? https://github.com/neayi/insights/commit/9580b74992f987b871c901329a76cac809f1af27

**Comment by guillaume-cozic** [comment]
@bertrandgorge oui
