### ISSUE TITLE
Il est possible d'avoir plusieurs lignes dans la table interactions pour le doublet "page_id / user_id"

### ISSUE THREAD

**Issue by bertrandgorge** [neayi/insights#82]
![image](https://user-images.githubusercontent.com/12585613/119517017-87152580-bd77-11eb-901c-195c7def38e6.png)

**Comment by bertrandgorge** [comment]
Une fois les lignes toutes supprimées je n'arrive pas à reproduire le problème...

**Comment by guillaume-cozic** [comment]
@bertrandgorge si tu retombes sur le problème on regardera
