### ISSUE TITLE
Il n'est pas possible de ne plus avoir d'avatar une fois qu'on en a choisi un

### ISSUE THREAD

**Issue by bertrandgorge** [neayi/insights#83]

**Comment by guillaume-cozic** [comment]
@bertrandgorge d'un point de vue utilisateur on rajoute un bouton pour supprimer l'avatar ?

**Comment by bertrandgorge** [comment]
Oui, une icône de poubelle par exemple, à côté du bouton stylo : https://fontawesome.com/v5.15/icons/trash-alt?style=regular

**Comment by bertrandgorge** [comment]
NB : j'ai déplacé la poubelle ! Mais apparemment le code ne fonctionne pas ?

**Comment by guillaume-cozic** [comment]
Traité

**Comment by bertrandgorge** [comment]
Hello @guillaume-cozic J'ai testé sur la dernière version du code, ça marche toujours pas. NB : j'ai bien fait un npm run dev
