### ISSUE TITLE
La description n'est pas protégée contre l'injection HTML

### ISSUE THREAD

**Issue by bertrandgorge** [neayi/insights#96]
Si on met du HTML dans la description, il est interprété.

**Comment by guillaume-cozic** [comment]
Traité

**Comment by bertrandgorge** [comment]
Je reproduis encore le problème : 

fdsfsfs fdsfsd
ligne 2
< te > <div> & &amp; € / \ ' * %

--> 

![image](https://user-images.githubusercontent.com/12585613/122445033-6ec4af00-cfa1-11eb-9207-7ca7b7e4db71.png)
